name: Staging deployment

on: 
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name,'stage')

env:
  DOCKER_IMAGE_NAME: Aashishm178-azure-ttt
  IMAGE-REPOSITORY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: Aashishm178-ttt-app